version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=database
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
